strongholdcoins/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

import account.views
from django.contrib import admin
from .views import SignupView
from . import views


urlpatterns = [

    url(r'^dashboard/user/(?P<user_pk>\d+)/order/(?P<order_pk>\d+)/edit',views.editOrder,name="editOrder"),
    url(r'^dashboard/order/(?P<order_pk>\d+)/delete',views.deleteOrder,name="deleteOrder"),
    url(r'^dashboard/user/profile/$',views.profile_view,name="userprofile"),
    # url(r'^dashboard/user/account/(?P<user_pk>\d+)',views.account_view,name="useraccount"),
    url(r'^dashboard/$',views.dashboard,name="dashboard"),

    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),


    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/signup/$",SignupView.as_view(),name="account_signup"),
    url(r"^account/", include("account.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

strongholdcoins/models.py
from django.db import models
from django.conf import settings


from django.db import models
from django.conf import settings

# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.utils.crypto import get_random_string
from django.utils.timezone import now
from django.db.models.signals import post_save
from django.dispatch import receiver



class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile')
    first_name = models.CharField(max_length=255, blank=True, null=True)
    surname = models.CharField(max_length=255, blank=True, null=True)
    birth_date = models.DateField(blank=True,null=True)
    profile_picture = models.ImageField(upload_to="profile_pictures/", blank=True, null=True)
    bio = models.TextField(max_length=500, blank=True, null=True)
    address = models.TextField(max_length=255, blank=True, null=True)
    identity_card = models.FileField(upload_to="identity_folder/", blank=True, null=True)
    phone = models.CharField(max_length=10, null=True,blank=True)

    def __str__(self):
        return self.user.username


    def _full_name(self):
        return self.first_name+" "+self.surname

    full_name = property(_full_name)


class Order(models.Model):

    BUY = 'B'
    SELL = 'S'
    INVEST = 'S'
    action = (
        ("B", "Buy"),
        ("S", "Sell"),
        ("I", "Invest"),
    )
    # PENDING = "P"
    AWAITING = "AW"
    APPROVED = "AP"
    WITHHELD = "W"
    status = (
        (AWAITING,"Awaiting Payment"),
        (APPROVED, "Approved"),
        (WITHHELD, "With Held"),
      
    )

    B = "Bitcoin"
    E = "Ethereum"
    L = "Litecoin"
    currencies = (
        (B, "Bitcoin"),
        (E, "Ethereum"),
        (L, "Litecoin"),
    )
    order_id = models.CharField(unique=True, max_length=10, blank=True, null=False,)
    wallet_address = models.CharField(blank=False, null=False, max_length=255)
    order_amount = models.DecimalField(decimal_places=2, max_digits=99999, blank=False, null=False)
    user = models.ForeignKey(User, related_name="user_order")

    order_status = models.CharField(choices=status, max_length=2, default=AWAITING, blank=False, null=False)
    crypto_currency = models.CharField(choices=currencies, default=B, blank=True, max_length=12)
    amount_of_coins = models.DecimalField(decimal_places=2, max_digits=99999, blank=False, null=False,default=0.00)
    commission_fee = models.DecimalField(decimal_places=2, max_digits=99999, blank=False, null=False,default=0.00)

    action = models.CharField(max_length=1, choices=action, default=BUY, blank=False)

    DEFAULT_PM = ''
    MOBILE_MONEY = "AMM"
    BANK_ACCOUNT_TRANSFER = "BAT"
    pm = (
        # (DEFAULT_PM,"Select Method"),
        (MOBILE_MONEY,"Mobile Money"),
        (BANK_ACCOUNT_TRANSFER,"Bank Account Transfer"),
    )
    
    MTN = "MTN"
    VODAFONE = "VODAFONE"
    AIRTEL = "AIRTEL"
    TIGO = "TIGO"
    mmv = (

        (MTN, "MTN"),
        (VODAFONE, "VODAFONE"),
        (AIRTEL, "AIRTEL"),
        (TIGO, "TIGO"),
    )

    payment_method = models.CharField(choices=pm, blank=False, null=False, max_length=4)

    
    GT = "GT Bank"
    ZB = "Zenith Bank"
    SB = "Stanbic Bank"
    EC = "EcoBank"
    UB = "UniBank"
    CB = "Cal Bank"

    banks = (
        (GT, "GT BANK"),
        (ZB, "ZENITH BANK"),
        (SB, "STANBIC BANK"),
        (EC, "ECOBANK"),
        (UB, "UNIBANK"),
        (CB, "CAL BANK"),
    )

    mobile_money_vendor = models.CharField(choices=mmv, blank=True, null=True, max_length=20)
    mobile_money_number = models.CharField(max_length=10, blank=True, null=True)

    bank = models.CharField(choices=banks, max_length=50, blank=True, null=True)
    bank_account_name = models.CharField(max_length=155, blank=True, null=True)
    bank_account_number = models.CharField(blank=True, null=True, max_length=16)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}".format(self.order_id)
 


class Event(models.Model):
	name = models.CharField(max_length=200)


class Rate(models.Model):

    BUY = 'B'
    SELL = 'S'
    INVEST = 'S'
    action = (
        ("B", "Buy"),
        ("S", "Sell"),
        ("I", "Invest"),
    )

    B = "BITCOIN"
    E = "ETHIRIUM"
    L = "LITHIUM"
    currency = (
        (B, "BITCOIN"),
        (E, "ETHIRIUM"),
        (L, "LITHIUM"),
        )

    # dollar_per_btc = models.DecimalField(decimal_places=2,max_digits=99999,blank=False, null=True)
    # btc_amount = models.DecimalField(decimal_places=2,max_digits=99999,blank=False, null=True)
    tax_fee = models.DecimalField(decimal_places=2,max_digits=100,blank=False, null=True)
    transaction_fee = models.DecimalField(decimal_places=2,max_digits=100,blank=False, null=True)
    action = models.CharField(max_length=1,choices=action,default=BUY,blank=True)
    # cryptocurrency = models.CharField(choices=currency,default=B,blank=True,max_length=12)

    def __str__(self):
        return self.action

strongholdcoins/forms.py
from django import forms
from django.forms.extras.widgets import SelectDateWidget

import account.forms

from django import forms
from django.utils.crypto import get_random_string
from django.forms import ModelForm, CharField, RadioSelect,Form
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Order,UserProfile
from PIL import Image

from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


class SignupForm(account.forms.SignupForm):
    # first_name = forms.CharField(max_length=100)
    # surname = forms.CharField(max_length=100)
    # birth_date = forms.DateField(widget=SelectDateWidget(years=range(1910,1991)))

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        del self.fields["username"]


class ProfileForm(ModelForm):

  class Meta:
    model = UserProfile
    fields = ('first_name','surname','birth_date','phone','address','profile_picture')

    def clean_content(self):
        content = self.cleaned_data['content']
        content_type = content.content_type.split('/')[0]
        if content_type in settings.CONTENT_TYPES:
            if content._size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(_('Please keep filesize under %s. Current filesize %s') % (
                filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(content._size)))
        else:
            raise forms.ValidationError(_('File type is not supported'))
        return content


class OrderForm(ModelForm):
    # wallet_address = CharField(required=True)
    # order_amount = CharField(required=True)

    MOBILE_MONEY = "AMM"
    BANK_ACCOUNT_TRANSFER = "BAT"

    pm = (
        ("", "Select Method"),
        (MOBILE_MONEY, "Mobile Money"),
        (BANK_ACCOUNT_TRANSFER, "Bank Account Transfer"),
    )
    payment_method = forms.CharField(max_length=3,widget=forms.Select(choices=pm),required=True)

    B = "Bitcoin"
    E = "Ethereum"
    L = "Litecoin"
    currencies = (
        (B, "Bitcoin"),
        (E, "Ethereum"),
        (L, "Litecoin"),
    )

    # amount_of_coins = forms.CharField(required=True)

    crypto_currency = forms.ChoiceField(choices=currencies, widget=forms.RadioSelect)

    class Meta:
        model = Order
        fields = ('order_id', 'wallet_address', 'order_amount', 'action', 'payment_method', 'bank','bank_account_name', 'bank_account_number','crypto_currency', 'mobile_money_vendor', 'mobile_money_number', 'amount_of_coins','commission_fee')

strongholdcoins/views.py
import account.views
from account.decorators import login_required
from .forms import SignupForm, OrderForm, ProfileForm
from .models import UserProfile, Order, Rate
from django.core.mail import send_mail, mail_admins

from django.http import JsonResponse

from django.contrib.auth import logout
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

from django.utils.crypto import get_random_string
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.core.urlresolvers import reverse
from django.utils import timezone
from django import template
from PIL import Image

# from coinbase.wallet.client import Client


LOGIN_URL = '/account/login/'
DOLLAR_RATE = 4.47


class SignupView(account.views.SignupView):
    form_class = SignupForm

    identifier_field = 'email'

    def generate_username(self, form):
        # do something to generate a unique username (required by the
        # Django User model, unfortunately)
        username = get_random_string(6, 'abcdefghijklmnopqrstuvwxyz0123456789')
        return username

    def update_profile(self, form):
        UserProfile.objects.create(
            user=self.created_user,

        )

    def after_signup(self, form):
        self.update_profile(form)
        super(SignupView, self).after_signup(form)


class LoginView(account.views.LoginView):
    form_class = account.forms.LoginEmailForm


# Dashboard
@login_required(login_url=LOGIN_URL)
def dashboard(request):
    if request.user.is_authenticated:
        user_account = get_object_or_404(User, pk=request.user.id)
        userprofile = UserProfile.objects.get(id=request.user.profile.id)
        btc = Rate.objects.get(action__startswith="B")
        # btc_current_amount = btc.dollar_per_btc
        # total_fee = float(btc.dollar_per_btc * ((100 + (btc.tax_fee + btc.transaction_fee)) / 100))
        transaction_fee = (((btc.tax_fee + btc.transaction_fee)) / 100)
        gh_transaction_fee = (float(transaction_fee) * float(DOLLAR_RATE))
        timenow = timezone.now()
        new_order = Order.objects.filter(user__id=request.user.id, order_status__exact="AW").order_by("-created_on")[:1]
        history_data = Order.objects.filter(user__id=request.user.id, created_on__lte=timezone.now()).order_by(
            "created_on")
        saving_order = OrderForm()

        if request.method == "POST":
            saving_order = OrderForm(request.POST)
            if saving_order.is_valid():
                saving_order = saving_order.save(commit=False)
                saving_order.order_id = "SHC" + get_random_string(7, '0123456789')
                saving_order.order_amount = float(saving_order.order_amount) - float(gh_transaction_fee)
                saving_order.user = request.user

                if saving_order.payment_method == "AMM":
                    saving_order.bank = "N/A"
                    saving_order.bank_account_name = "N/A"
                    saving_order.bank_account_number = "N/A"
                elif saving_order.payment_method == "BAT":
                    saving_order.mobile_money_vendor = "N/A"
                    saving_order.mobile_money_number = "N/A"
                else:
                    saving_order.bank = "N/A"
                    saving_order.bank_account_name = "N/A"
                    saving_order.bank_account_number = "N/A"

                saving_order.save()

                messages.add_message(request, messages.SUCCESS,
                                     "Your order with REFERENCE ID {} was added successfully!".format(
                                         saving_order.order_id))

                mail_admins(
                    'STRONGHOLDCOINS: ORDER REQUESTED',
                    '{} has placed an order with ID: {}, please check at '
                    'https://strongholdcoins.com/admin/strongholdcoins/order/ check to review'.format(
                        request.user.username, saving_order.order_id),
                    fail_silently=False
                )

                order = OrderForm()
                return HttpResponseRedirect('/dashboard', {'form': order})
            else:
                messages.error(request, 'There was an error, try again later: {}'.format(saving_order.errors))

    return render(request, "strongholdcoins/dashboard_views/dashboard.html",
                  {'user_account': user_account, 'timenow': timenow, 'form': saving_order, 'new_order': new_order,
                   'history': history_data, 'userprofile': userprofile, 'btcrate': btc,
                   'transaction_fee': transaction_fee})


# Dashboard Edit
def editOrder(request, user_pk, order_pk):
    if request.user.is_authenticated:
        new_order = Order.objects.filter(user__id=request.user.id, order_status__exact="AW").order_by("-created_on")[:1]
        history_data = Order.objects.filter(user__id=request.user.id, created_on__lte=timezone.now()).order_by("created_on")
        userprofile = UserProfile.objects.filter(user__id=request.user.id)
        btc = Rate.objects.get(action__startswith="B")
        transaction_fee = ((100 + (btc.tax_fee + btc.transaction_fee)) / 100)
        order_to_edit = get_object_or_404(Order, pk=order_pk)
        orderform = OrderForm(instance=order_to_edit)

        pth = "/dashboard/user/{}/order/{}/edit".format(user_pk, order_to_edit.id)

        if request.method == "POST":
            orderform = OrderForm(request.POST, instance=order_to_edit)
            if orderform.is_valid():
                orderform.save()

                messages.add_message(request, messages.SUCCESS,
                                     "Your order with REFERENCE ID {} was updated successfully!".format(order_to_edit.order_id))
                mail_admins(
                    'STRONGHOLDCOINS: ORDER EDITED',
                    '{} edited an order with ID: {}, please check at '
                    'https://strongholdcoins.com/admin/strongholdcoins/order/ check to review'.format(
                        request.user.username, order_to_edit.order_id),fail_silently=False)
            else:
                messages.error(request, 'There was an error, try again later')

    return render(request, 'strongholdcoins/dashboard_views/dashboard.html',
                  {'form': orderform, 'new_order': new_order, 'history': history_data, 'pth': pth,
                   'userprofile': userprofile, 'order_to_edit': order_to_edit, 'btcrate': btc,
                   'transaction_fee': transaction_fee})



def deleteOrder(request, order_pk):
    if request.user.is_authenticated:
        if request.method == "POST":
            order_to_delete = get_object_or_404(Order, pk=order_pk).delete()
            messages.add_message(request, messages.SUCCESS,"Your order with was deleted successfully!")
        return HttpResponseRedirect(reverse('dashboard'))


def profile_view(request):
    if request.user.is_authenticated:
            user_id = request.user.id
            userprofile = get_object_or_404(UserProfile,id=request.user.profile.id)
            profile_form = ProfileForm(instance=userprofile)
            if request.method == "POST":
                profile_form = ProfileForm(data=request.POST, files=request.FILES, instance=userprofile)
                if profile_form.is_valid:
                    profile_form.save()
                    return HttpResponseRedirect('/dashboard/user/profile', {'profile_form': profile_form, 'userprofile': userprofile})
            return render(request, "strongholdcoins/dashboard_views/profile.html",{'profile_form': profile_form, 'userprofile': userprofile})
    else:
        return HttpResponseNotFound('<h1>Bad Bot! Page not found</h1>')

# def account_view(request, user_pk):
#     userprofile = UserProfile.objects.filter(user__id=request.user.id)
#     user_id = request.user.id
#     if user_id == int(user_pk):
#         user_account = get_object_or_404(User, pk=user_pk)
#         account_form = UserAccountForm(instance=user_account)
#         if request.method == "POST":
#             account_form = UserAccountForm(request.POST, instance=user_account)
#             if account_form.is_valid:
#                 account_form.save()
#         return render(request, "strongholdcoins/dashboard_views/account.html",
#                       {'account_form': account_form, 'user_account': user_account, 'user_profile': user_profile})
#     else:
#         return HttpResponseNotFound('<h1>Bad Bot! Page not found</h1>')

strongholdcoins/templates/strongholdcoins/dashboard_views/actions_menu.html
{% load staticfiles %}{% load account_tags %}{% load account_tags %}
<div class="sidebar ">
    <nav class="sidebar-nav ">
        <ul class="nav ">

            <div id="profile-pic">

                {% if request.user.profile.profile_picture == '' %}
                  <div class="pp" style="max-height:200px; overflow:hidden;">
                <img src="{% static 'strongholdcoins/img/placeholder.png' %}" style="object-fit: cover;height: 200px;
                width: 200px
                !important; overflow: hidden;padding:20px" alt="">
                  </div>
                {% else %}
                <div class="pp" style="max-height:200px; overflow:hidden;">
                    <img src="{{request.user.profile.profile_picture.url}}" style="object-fit: cover;height: 200px;
                    width: 200px
                !important; overflow: hidden;padding:20px" alt="">
                </div>
                {% endif  %}

            </div>


            <li class="nav-item"><a href="" class="nav-link">
                {% if request.user.profile.first_name == "" %}
                <h5 class="lead">{{ request.user.email }} </h5>
                {%else %}
                <h5 class="lead">{{ request.user.profile.full_name }} </h5>
                {% endif %}
            </a></li>
            <li class="nav-item"><a href="{% url 'dashboard' %}" class="nav-link"><i class="fa fa-dashboard fa-4x" aria-hidden="true"></i>Dashboard</a></li>
            <li class="nav-item"><a href="{% url 'account_settings' %}" class="nav-link"><i class="fa fa-cog"></i> Account</a></li>
        
            <li class="nav-item"><a href="{% url 'userprofile' %}" class="nav-link"><i class="fa fa-vcard fa-4x" aria-hidden="true"></i>Profile</a></li>

            <li class="nav-item"><a href="" class="nav-link"></a></li>
        </ul>
    </nav>
</div>

strongholdcoins/templates/strongholdcoins/dashboard_views/calculator.html
{% load humanize %}
<div class="" id="newsheadline">

    <h6>Select your cryptocoin</h6>
    <hr>
 <div class="form-row">
        <div class="form-group col-md-4">
        <h6>Bitcoin
        <input type="radio" name="coin" value="Bitcoin">
      </h6>
    </div>
        <div class="form-group col-md-4">
        <h6>Ethireum
        <input type="radio" name="coin" value="Ethereum">
      </h6>
    </div>

        <div class="form-group col-md-4">
        <h6>Litecoin
        <input type="radio" name="coin" value="Litecoin">
      </h6>
    </div>

 </div>
    <hr>
    <form id="buyingform">
    <!--<h6>Buying</h6>-->
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="inputEmail4" class="col-form-label">Amount (USD)</label>
                <input type="number" class="form-control bg-dark border-pher text-white" min="10" name="amount1" id="amount1">
            </div>
            <div class="form-group col-md-4">
                <label for="inputPassword4" class="col-form-label">Coins</label>
                <input type="number" class="form-control bg-dark border-pher text-white" hidden="True" id="h_totsfee"
                       readonly="true" value="{{total_fee}}">
                <input type="number" class="form-control bg-dark border-pher text-white" id="amount_of_bitcoins1"
                       readonly="true">
            </div>
             <div class="form-group col-md-4">
                <label for="inputPassword4" class="col-form-label">Fee(USD)</label>
                <input type="number" class="form-control bg-dark border-pher text-white" id="key_fee"
                       value="{{transaction_fee}}"
                       hidden=""True
                       readonly="true">
                <input type="number" class="form-control bg-dark border-pher text-white" id="transaction_fee1"
                       readonly="true">
            </div>
<div class="form-row col-md-12">
                <label class="col-form-label">Amount to be Paid (GHC)</label>
                <input type="number" class="form-control bg-dark border-pher text-white" id="amountTotal"
                       readonly="true">
            </div>
        </div>

    </form>


    
    
</div>

strongholdcoins/templates/strongholdcoins/dashboard_views/edit-order-form.html
{% load widget_tweaks %}
{{proth}}
<form action="" method="POST" class=" form bg-dark" id="orderFormMain">

{% include "strongholdcoins/dashboard_views/toast-messages.html"%}
    {% csrf_token %}
    <div class="field">
        {% render_field form.order_id class+="form-control"  readonly="True" hidden="True"%}
    </div>

    <div class="field form-group bg-dark">
        <label>{{form.wallet_address.label}}</label> {% render_field form.wallet_address  class+="text-white form-control bg-dark border-pher" placeholder="Enter your wallet address" required="required" autofocus="True" %}
    </div>

    <div class="form-row">
 <label>{{form.crypto_currency.label}}</label>
            {{form.crypto_currency | attr:'required' | add_class:"radio-inline cryptocoin"}}

    </div>

    <div class="form-row ">
        <div class="col-md-4 form-group ">
            <label>{{form.order_amount.label}} (GHC)</label>
            {{form.order_amount | attr:'required' | add_class:"form-control bg-dark text-white border-pher"}}
            {{form.amount_of_coins | attr:'hidden' | add_class:"form-control bg-dark text-white border-pher"}}

            <input type="hidden" id="id_commission_fee" name="commission_fee" value="" class="form-control">

        </div>

 
        <div class="col-md-4 form-group ">
            <label>{{form.action.label}}</label>
            {{form.action | attr:'required'|add_class:"form-control text-white bg-dark text-white border-pher"}}
        </div>
        <div class="col-md-4 form-group ">
            <label>{{form.payment_method.label}}</label>
            {{form.payment_method |attr:'required'|add_class:"form-control bg-dark border-pher text-white"}}
        </div>
    </div>



    <div id="bankForm" class="form-row">
        <div class="field form-group  col-md-4">
            <label>{{form.bank.label}}</label> {{form.bank |add_class:"form-control text-white bg-dark border-pher"}}
        </div>
        <div class="field form-group  col-md-4">
            <label>{{form.bank_account_name.label}}</label> {{form.bank_account_name| add_class:"text-white form-control bg-dark border-pher"}}
        </div>

        <div class="field form-group  col-md-4">
            <label>{{form.bank_account_number.label}}</label> {{form.bank_account_number | add_class:" text-white form-control bg-dark border-pher"}}
        </div>
    </div>



    <div id="mobilemoneyForm" class="form-row">
        <div class="field  form-group  col-md-6">
            <label>{{form.mobile_money_vendor.label}}</label> {{form.mobile_money_vendor| add_class:"form-control text-white bg-dark border-pher"}}
        </div>

        <div class="field form-group  col-md-6">
            <label>{{form.mobile_money_number.label}}</label> {{form.mobile_money_number| add_class:"form-control text-white bg-dark border-pher"}}
        </div>
    </div>

    <div class="field">

        <input type="hidden" name="user_id" value="{{ request.user.id }}">
    </div>


    <div class="field">
        {% if request.path == pth %}
        <button type="submit" class="btn btn-sm btn-primary">Update Order</button> {% else %}
        <button type="submit" class="btn btn-sm btn-success text-white">Make Order</button> {% endif %}
    </div>
</form>

strongholdcoins/templates/strongholdcoins/dashboard_views/edit_order.html
{% load widget_tweaks %}

<form action="" method="POST" class=" ui form attached fluid segment">

    {% csrf_token %}
    <div class="field">
        <input type="hidden" id="id_order_id" name="order_id" value="">
    </div>
    <div class="field">
        <label>{{form.wallet_address.label}}</label> {% render_field form.wallet_address placeholder="Enter your wallet address" required="required" %}
    </div>

    <div class="fields four ">
        <div class="field">
            <label>{{form.order_amount.label}}</label> {{form.order_amount | attr:'required'}}
        </div>

        <div class="field">
            <label>{{form.order_amount.label}}</label> {{form.order_amount | attr:'required'}}
        </div>
        <div class="field">
            <label>{{form.action.label}}</label> {{form.action | attr:'required'}}
        </div>
        <div class="field ">
            <label>{{form.payment_method.label}}</label> {{form.payment_method | attr:'required'}}
        </div>
    </div>


    <div id="mobilemoneyForm">
        <div class="field ">
            <label>{{form.mobile_money_vendor.label}}</label> {{form.mobile_money_vendor}}
        </div>

        <div class="field ">
            <label>{{form.mobile_money_number.label}}</label> {{form.mobile_money_number}}
        </div>
    </div>

    <div id="bankForm">
        <div class="field">
            <label>{{form.bank.label}}</label> {{form.bank}}
        </div>
        <div class="field ">
            <label>{{form.bank_account_name.label}}</label> {{form.bank_account_name}}
        </div>

        <div class="field ">
            <label>{{form.bank_account_number.label}}</label> {{form.bank_account_number}}
        </div>
    </div>

    <div class="field">
        <input type="hidden" name="user_id" value="{{ request.user.id }}">
    </div>
    <div class="field">
        <button type="submit" class="ui button teal">Make Order</button>
    </div>
</form>

strongholdcoins/templates/strongholdcoins/dashboard_views/history_data.html
{%load humanize %}
<table class="table table-striped table-inverse table-sm table-hover table-responsive" id="history">

    <thead class="">
        <tr>
            <th>Date Created</th>
            <th>Reference</th>
            <th>Wallet Address</th>
            <th>Payment Method</th>
            <th>Bank</th>
            <th>Bank Account</th>
            <th>Bank #</th>
            <th>MM Vendor</th>
            <th>MM Number</th>
            <th>Order Status</th>
        </tr>
    </thead>

    <tbody class="">
        {% for d in history %}
        <tr>
            <td>{{d.created_on | date:"d-m-Y:H:i"}}</td>
            <!--<td><a href="{% url 'editOrder' user_pk=request.user.id order_pk=d.id %}">{{d.order_id}}</a></td>-->
            <td>{{d.order_id}}</td>
            <td>{{d.wallet_address}}</td>
            <td>{% if d.payment_method == "AMM" %} Mobile Money {% else %} Bank Transfer {% endif %}</td>
            <td>{% if d.bank == "" %} ------- {% else %} {{d.bank}} {% endif %}</td>
            <td>{% if d.bank_account_name == "" %} ------- {% else %} {{d.bank_account_name}} {% endif %} </td>
            <td>{{d.bank_account_number}}</td>
            <td>{{d.mobile_money_vendor}}</td>
            <td>{{d.mobile_money_number}}</td>
            <td>
                {% if d.order_status == "AW" %} <span class="btn btn-sm btn-warning">Pending Payment</span> {% elif d.order_status == "AP" %} <span class="btn btn-sm btn-success">Approved Transaction</span> {% endif %}


            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>

strongholdcoins/templates/strongholdcoins/dashboard_views/toast-messages.html
{% if messages %}
<div class="alert alert-info">
    {% for message in messages %}
    <small {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</small>
    {% endfor %}

</div>
{% endif %}